os: linux
dist: bionic
language: perl
perl:
  - "5.30"
env:
  - PERL_CPANM_OPT="--quiet --notest"
jobs:
  include:
    - stage: test
      cache:
        directories:
          - ${PERLBREW_ROOT}/perls/${PERLBREW_PERL}/lib
          - ${PERLBREW_ROOT}/perls/${PERLBREW_PERL}/bin
      before_install:
        - dzil authordeps --missing | cpanm
      install:
        - dzil listdeps --develop --missing | cpanm
      before_script:
        - perlcritic lib t xt
      script:
        - dzil test --all
    - stage: test
      os: windows
      language: shell
      git:
        autocrlf: input
      cache:
        directories:
          - /c/Strawberry
      before_install:
        - test -d /c/Strawberry/perl || cinst -y strawberryperl
        - export "PATH=/c/Strawberry/perl/site/bin:/c/Strawberry/perl/bin:/c/Strawberry/c/bin:$PATH"
        - export "PERL5LIB=/c/Strawberry/perl/site/lib:/c/Strawberry/perl/vendor/lib:/c/Strawberry/perl/lib"
        - ln -snf /c/Strawberry/perl/bin/perl /bin/perl
        - cpanm Dist::Zilla
        - dzil authordeps --missing | cpanm
      install:
        - dzil listdeps --develop --missing | cpanm
      before_script:
        - perlcritic lib t xt
      script:
        - dzil test --all
    - stage: test
      os: osx
      osx_image: xcode11.5
      language: shell
      cache:
        directories:
          - /usr/local/Cellar/perl
      addons:
        homebrew:
          packages:
            - perl
            - cpanminus
      before_install:
        - export PERL_VERSION="$(brew list --versions perl | cut -d' ' -f 2)"
        - export "PATH=/usr/local/Cellar/perl/${PERL_VERSION}/bin:${PATH}"
        - cpanm Dist::Zilla
        - dzil authordeps --missing | cpanm
      install:
        - dzil listdeps --develop --missing | cpanm
      before_script:
        - perlcritic lib t xt
      script:
        - dzil test --all
